# TODO: remove the below comment:
# This workflow needs to be merged as a test workflow prior to the implementation code being merged.
# actions/checkout should infer its 'ref' input and check out the repo using the tag associated with the test release.
name: Test Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  debug: # TODO: remove this job after this workflow is confirmed to work
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  pr-comment-on-release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.name, 'v0.0.0-test.')" # Match releases created by both test-include.yml and test-exclude.yml
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          include_regex: "/v0\\.0\\.0-test\\.include\\.*./g" # Only include releases created by test-include.yml
