name: Test Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  pr-comment-on-release:
    if: "startsWith(github.event.name , 'v0.0.0-test')" # Match only releases created by test-include.yml and test-exclude.yml
    uses: ./action.yaml
    with:
      include_regex: "/v0\\.0\\.0-test-include\\.*./g" # Only include releases created by test-include.yml
