name: Test Positive
on:
  pull_request: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: gh release create v1.0.0-test-${{ github.sha }} --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./
        id: current
        with:
          include_regex: "/v1\\.0\\.0-test-*./g"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-regex: "^These changes were released in .*test-${{ github.sha }}.*$"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - run: gh release delete v1.0.0-test-${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
